# Use root/example as user/password credentials
version: '3.1'

services:

  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      REDIS_PORT_NUMBER: '6379'
    ports:
      - "6379:6379"

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"